### ISSUE TITLE
Error, same package as this project

### ISSUE THREAD

**Issue by ArthurSav** [ppamorim/RecyclerRenderers#5]
Downloaded the project and this was the first error that occured. Solved it by following the error tip but it should propably resolved here

Error:Execution failed for task ':app:processDebugResources'.

> Error: A library uses the same package as this project: com.github.ppamorim.recyclerrenderers
>   You can temporarily disable this error with android.enforceUniquePackageName=false
>   However, this is temporary and will be enforced in 1.0

**Comment by ppamorim** [comment]
Will be fixed on the next release.
